### ISSUE TITLE
It always reports "not up to date" with v1 lock file

### ISSUE THREAD

**Issue by atleta** [MBuchalik/package-lock-utd#1]
I'm using a v1 lock file because I have an older version of npm in deployment and the tool keeps reporting the lock file being not up to date.  I'm generating the lock file with `npm i --package-lock-only --lockfile-version 1`

It also issues a warning about fetching some extra metadata every time I run it. The warning only appears *after* the run is completed and states that it's a one-time fixup, still it happens every time.

It does work with v2 and v3.

**Comment by MBuchalik** [comment]
If I understood it correctly, you are using an outdated version of npm somewhere in your deployment process. Let's call this version `X`. This npm version only supports lockfiles in version 1.  
Next to this, you are using a CI environment (?) where you, among others, make calls to `package-lock-utd`. In this CI environment, you are using a more up to date version of npm. 
 
Is this summary correct? Or have I misunderstand something?

---

> the tool keeps reporting the lock file being not up to date

`package-lock-utd` makes calls to the the globally installed npm binary to perform its checks. Is it possible for you to downgrade the npm binary in your CI environment to version `X`?

> states that it's a one-time fixup, still it happens every time.

Internally, my script calls `npm install` and, after the checks have completed, reverts all changes. The output you see is most likely the output from the call to `npm install`. npm probably updates the lockfile version with this call (which then gets reverted again). My recommendation is again to check if you can use the older npm binary in version `X`.

The goal of `package-lock-utd` is the following:

```
If npm install would somehow modify package-lock.json, package-lock-utd exits with a non-zero exit code.
```
(This was quoted from the Readme, see https://github.com/MBuchalik/package-lock-utd/blob/ab5666eaefa8fd08c7478fb55860434406aa1710/README.md)


I think that this goal has actually been met here. Because whenever you run `npm install`, in your setup, `package-lock.json` will get modified. That's why I currently only see the option of downgrading npm to version `X`.

**Comment by atleta** [comment]
> If I understood it correctly, you are using an outdated version of npm somewhere in your deployment process. Let's call this version X. This npm version only supports lockfiles in version 1.

Yes, this is about right. We have npm 6.x in production and use npm 9.x in development. Now I found that 6.x supports lockfile version 2 and that works with package-lock-utd/npm 9. However, we have been using v1 since npm does not automatically update the lock file version and we seem to have started the project with an npm version that initially created lock files of version 1. (Which means that there might be other long-running projects with a v1 package file and they'll experience a similar problem.)

> Is it possible for you to downgrade the npm binary in your CI environment to version

Nope. However, just to confirm, in my specific case the issue went away with switching to lock file version 2.

> The output you see is most likely the output from the call to npm install. 

That's correct:
```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
It seems like package-lock.json is not up to date. Try running "npm install".
```
Now I don't know what causes it, but just FYI, it works with npm 9.x and lock file version 2 (while npm 9.x, by default, would use lock file version 3).

I have looked into how it works and I found that the problem is that if the lock file is of version one and you do an `npm install --package-lock-only` then it will upgrade it to v3 (or, I guess, whatever the current version is). If it was v2 to begin with then it's kept at v2. In hindsight, the above message from npm hints at this happening.

Now if you add `--lockfile-version 1` to the `npm install` call then it will keep it at v1 and then the comparison will work as intended. What I would do, I guess, is that I would get the lockfile version from the lock file and append it with the `--lockfile-version` parameter to the npm call in line 38: https://github.com/MBuchalik/package-lock-utd/blob/ab5666eaefa8fd08c7478fb55860434406aa1710/src/cli.ts#L38 . I know it's unlikely that others run into it but it's a small fix and npm might do a similar forced lock file upgrade in the future as well.

**Comment by MBuchalik** [comment]
Thanks for the information! In my projects, if someone tried to commit an outdated lockfile version (e.g. because they maybe messed up something), I would actually want CI to fail. And if npm gets a new lockfile version and performs the auto-update, I would actually also appreciate it if CI informed me about this.    
So my first idea was to make this an optional flag. I.e. you would pass a flag like `--ignore-outdated-lockfile-version` when calling package-lock-utd, and this flag would make package-lock-utd behave as you suggested.

Now, while looking at this in more detail, I noticed something. I am curious if this might work in your setup. Could you create an `.npmrc` file right next to your `package.json`/`package-lock.json` files, and  add the following content?

```
lockfile-version = 1
```

Now, npm should automatically treat every call to `npm install` in the same way as if you manually wrote `npm install --lockfile-version 1`. And that means: This should also make `package-lock-utd` work as expected. In a small experiment, this did seem to work fine for me.

Does this work for you? And would this be an option to fix your issue?


---


Side note: I am not completely against adding a separate parameter to this package. But if there is an easier and more flexible way, then I'd prefer that option. And if the trick with the `.npmrc` file works, then I can also recommend this if a similar issue occurs with another setting.

**Comment by MBuchalik** [comment]
I am closing this issue for now since I am quite confident that my workaround should be applicable in the scenario you described. If you still experience problems or have any questions, feel free to comment on this issue or to create a new one.
